export type PublicationStatus = "draft" | "review" | "approved" | "published" | "rejected";
export type Approval = { publicationStatus: PublicationStatus; approvalDate: string | null };
export type SocialLink = { label: string; url: string; confirmed?: boolean };
export type ImageAsset = { src: string; alt: string; width: number; height: number; filename: string; bytes?: number };
export type MediaRecord = Approval & { assetId: string; src: string; filename: string; description: string; alt: string; decorative: boolean; routeUsage: string[]; copyrightHolder: string; source: string; licence: string; permissionStatus: "pending" | "approved" | "rejected"; usageRestriction: string; expiry: string | null; bytes?: number };
export type PersonRecord = Approval & { id: string; name: string; role: string; shortBiography: string; longBiography?: string; portrait?: ImageAsset; socialLinks?: SocialLink[]; experienceSummary?: string[]; approach?: string; values?: string[]; location?: string; imageRightsConfirmed: boolean };
export type TestimonialRecord = Approval & { id: string; clientName: string; businessName?: string; role?: string; quote: string; projectReference?: string; approvalConfirmed: boolean; consentDate: string | null };
export type ProjectRecord = Approval & { slug: string; clientName: string; industry?: string; services: string[]; summary: string; challenge?: string; strategicDirection?: string; creativeExecution?: string; deliverables?: string[]; gallery?: ImageAsset[]; brandRevealVideo?: { src: string; poster: string; label: string; captions?: string; filename: string; posterFilename: string; bytes?: number }; websitePreview?: { desktop: ImageAsset; tablet?: ImageAsset; mobile?: ImageAsset; url?: string }; beforeAndAfter?: { before: ImageAsset; after: ImageAsset; label: string }; timeline?: { label: string; detail: string }[]; results?: string; testimonial?: TestimonialRecord; relatedProjects?: string[]; mediaRightsConfirmed: boolean; clientPublicationApproved: boolean; publicationDate: string | null; openGraphArtwork?: ImageAsset };
export type OwnerContent = {
  business: { publicName: string; legalName: string; email: string | null; emailConfirmed: boolean; telephone: string | null; telephoneConfirmed: boolean; whatsapp: string | null; whatsappConfirmed: boolean; location: string; locationConfirmed: boolean; serviceArea: string; serviceAreaConfirmed: boolean; hours: string; socialLinks: SocialLink[]; copyrightHolder: string; legalContact: string; privacyContact: string; termsContact: string; domain: string; canonicalUrl: string; ownerConfirmed: boolean; approvalDate: string | null };
  brand: { tagline: string; description: string };
  founders: PersonRecord[]; team: PersonRecord[]; testimonials: TestimonialRecord[]; projects: ProjectRecord[];
  legal: { privacyApproval: boolean; privacyPublicationStatus: PublicationStatus; privacyVersion: string; termsApproval: boolean; termsPublicationStatus: PublicationStatus; termsVersion: string; cookiePolicyRequired: boolean | null; analyticsPolicyApproved: boolean; legalReviewer: string; approvalDate: string | null; outstandingIssues: string[]; mediaUseWordingApproved: boolean; clientPublicationWordingApproved: boolean; contactDataWordingApproved: boolean };
  media: MediaRecord[];
  openGraph: { defaultArtwork: (ImageAsset & Approval) | null; routeArtwork: Array<ImageAsset & Approval & { route: string }>; projectArtwork: Array<ImageAsset & Approval & { projectSlug: string }> };
  verification: { domainValidated: boolean; realDeviceSignoff: boolean; lighthouseVerified: boolean; lighthouseEvidenceDate: string | null; testsPassed: boolean; eslintPassed: boolean; typeScriptPassed: boolean; productionBuildPassed: boolean; routeChecksPassed: boolean; cspPassed: boolean; accessibilityCriticalChecksPassed: boolean; contactFlowPassed: boolean; highSeveritySecurityIssuesResolved: boolean; launchApprovalRecorded: boolean };
};
export const PUBLICATION_STATUSES: readonly PublicationStatus[];
export const ownerContent: OwnerContent;
