import Image from "next/image";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import AtelierVisual from "@/components/AtelierVisual";

const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
const loop=[["01","Specify","Translate ambition into an outcome, constraints, acceptance criteria and a clear definition of ready."],["02","Inspect","Understand the current business, audience, assets, digital presence, category context and evidence before changing anything."],["03","Direct","Choose the perception, message and visual territory that should govern every subsequent decision."],["04","Craft","Build the smallest coherent identity, digital or launch system that satisfies the agreed direction."],["05","Verify","Interrogate the work across content, responsive behaviour, accessibility, performance, links, media and real user journeys."],["06","Critique","Compare the result against the intended outcome and evidence—not against how impressive the work feels internally."],["07","Repair","Resolve failures at their root cause, then repeat the relevant checks rather than hiding defects with cosmetic patches."],["08","Release","Approve, organise and release a tested artifact with a clear handover, support boundary and known rollback path."]] as const;
const contracts=[["Outcome","What must be visibly and commercially different when the work is complete?"],["Evidence","What real assets, proof, tests and observations are allowed to support the decisions?"],["Change","What may change, what must remain intact and what requires explicit approval?"],["Quality","What must pass before the work is permitted to carry the client’s name?"]] as const;
export const metadata={title:"Process · The Atelier Standard",description:"An evidence-driven Prime Presence Atelier process from specification and direction through craft, verification, repair and release.",alternates:{canonical:"/process"}};

export default function Page(){return <PageShell eyebrow="Process · The Atelier Standard" title="Beautiful is not the finish line." intro="The work is complete only when the intended impression survives implementation, scrutiny and the real conditions in which a customer will experience it.">
<section className="relative -mx-5 overflow-hidden border-y border-white/[.07] bg-[#050504] px-5 py-16 sm:-mx-8 sm:px-8 sm:py-24 lg:-mx-12 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1180px] gap-12 lg:grid-cols-[.78fr_1.22fr] lg:items-center lg:gap-20"><div><p className="eyebrow">The governing principle</p><h2 className="mt-6 font-[family-name:var(--font-cormorant)] text-[clamp(3.2rem,7vw,6.4rem)] leading-[.85] tracking-[-.04em] text-[#f4ede2]">Evidence over <span className="italic text-[#d5a84d]">confidence.</span></h2><p className="mt-7 max-w-xl text-[15px] leading-8 text-white/48">A direction is not approved because it sounds convincing. A website is not finished because it compiles. Every important claim about the work should be supported by something observable: the brief, the asset, the browser, the test or the released experience.</p><Link href="/work" className="mt-7 inline-flex min-h-11 items-center gap-5 border-b border-[#c99a3c]/55 text-[9px] font-bold uppercase tracking-[.17em] text-[#e0b75f]">See the Evidence <span>→</span></Link></div><AtelierVisual variant="process" label="Prime Presence evidence-driven execution loop"/></div></section>

<section className="mt-20 sm:mt-28"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow">Before production</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(2.8rem,5vw,4.8rem)] leading-[.9] text-[#f2eadf]">Four contracts.<br/><span className="italic text-[#d5a94f]">No ambiguity.</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-white/42">These are not paperwork for its own sake. They prevent the project from drifting toward something attractive but commercially wrong.</p></div><div className="grid gap-px bg-white/[.08] sm:grid-cols-2">{contracts.map(([t,b],i)=><article key={t} className="min-h-[210px] bg-[#070604] p-6 sm:p-7"><p className="text-[8px] font-bold tracking-[.2em] text-[#c99a3c]">0{i+1}</p><h3 className="mt-7 font-[family-name:var(--font-cormorant)] text-3xl text-[#f2eadf]">{t} contract.</h3><p className="mt-4 text-sm leading-7 text-white/44">{b}</p></article>)}</div></div></section>

<section className="mt-20 sm:mt-28"><div className="mb-10 max-w-3xl"><p className="eyebrow">The execution loop</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(3rem,6vw,5.6rem)] leading-[.88] text-white">Direction becomes <span className="italic text-[#d5a94f]">proof.</span></h2></div><div className="grid gap-px bg-white/[.08] sm:grid-cols-2 lg:grid-cols-4">{loop.map(([n,t,b],i)=><article key={n} className="group min-h-[310px] bg-[#070604] p-6 transition-colors duration-300 hover:bg-[#0b0906] sm:p-7"><div className="flex items-center justify-between"><p className="text-[9px] font-bold tracking-[.2em] text-[#c99a3c]">{n}</p>{i<loop.length-1&&<span className="text-[#c99a3c]/35">→</span>}</div><h3 className="mt-12 font-[family-name:var(--font-cormorant)] text-3xl text-[#f2eadf] sm:text-4xl">{t}<span className="text-[#c99a3c]">.</span></h3><p className="mt-5 text-sm leading-7 text-white/44">{b}</p></article>)}</div></section>

<section className="mt-20 overflow-hidden border border-white/[.08] bg-[#070604] sm:mt-28"><div className="grid lg:grid-cols-[1.08fr_.92fr]"><div className="relative min-h-[380px] sm:min-h-[520px]"><Image src={`${basePath}/media/ppa-brand-identity-1.webp`} alt="Prime Presence Atelier identity system used as a visual quality reference" fill sizes="(max-width:1024px) 100vw,55vw" className="object-cover object-center"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(5,5,4,.55),transparent_55%)]"/><div className="absolute bottom-6 left-6 border-l border-[#c99a3c]/65 bg-black/55 px-4 py-3 backdrop-blur-md"><p className="text-[8px] font-bold uppercase tracking-[.2em] text-[#d5aa52]">Quality reference</p><p className="mt-1 text-[9px] uppercase tracking-[.14em] text-white/45">Real Prime Presence system</p></div></div><div className="flex items-center p-7 sm:p-10 lg:p-12"><div><p className="eyebrow">The verification gate</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(3rem,6vw,5.4rem)] leading-[.88] tracking-[-.035em] text-white">If it only works in the presentation,<br/><span className="italic text-[#d7aa4f]">it does not work.</span></h2><p className="mt-6 max-w-xl text-[15px] leading-8 text-white/48">Digital work is reviewed where it actually lives: narrow phones, large displays, keyboard navigation, zoom, reduced motion and the browsers customers use. Media must remain deliberate. Copy must remain credible. Conversion paths must remain usable.</p></div></div></div></section>

<section className="relative mt-20 overflow-hidden border border-[#c99a3c]/15 bg-[#070604] sm:mt-28"><div className="grid lg:grid-cols-[.9fr_1.1fr]"><div className="relative min-h-[340px] overflow-hidden lg:min-h-[480px]"><Image src={`${basePath}/media/ppa-hero-collateral.webp`} alt="Prime Presence Atelier collateral arranged as a final quality reference" fill sizes="(max-width:1024px) 100vw,45vw" className="object-cover object-center"/><div className="absolute inset-0 bg-[linear-gradient(90deg,transparent_45%,rgba(7,6,4,.75))]"/></div><div className="flex items-center p-7 sm:p-10 lg:p-12"><div><p className="eyebrow">Definition of done</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(3rem,6vw,5.5rem)] leading-[.88] tracking-[-.035em] text-white">Not when it looks finished.<br/><span className="italic text-[#d7aa4f]">When it is provably ready.</span></h2><p className="mt-6 max-w-xl text-sm leading-7 text-white/44">The final standard is a coherent brand-specific experience, functioning conversion paths, intentional responsive behaviour, accessible interaction, controlled performance and a verified release.</p><Link href="/contact" className="button-primary mt-8">Discuss the Direction</Link></div></div></div></section>
</PageShell>}
