import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import PageShell from "@/components/PageShell";
const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
export const metadata:Metadata={title:"Prime Presence Connect — Coming Soon",description:"Prime Presence Connect is an upcoming premium mobile-first digital introduction product by Prime Presence Atelier.",alternates:{canonical:"/connect"}};
const clues=[["01","Share","One deliberate handoff. No searching, explaining or sending someone through a maze."],["02","Connect","The details that matter, presented for the moment someone is ready to act."],["03","Remember","A digital introduction designed to leave more than a saved contact behind."]] as const;
export default function Page(){return <PageShell eyebrow="Prime Presence product · In development" title="Something is coming." intro="We are building a different kind of digital introduction. We are not ready to show you all of it yet.">
<section className="relative -mx-5 overflow-hidden border-y border-white/[.07] bg-[#030302] sm:-mx-8 lg:-mx-12"><div className="relative min-h-[720px] sm:min-h-[780px]"><Image src={`${basePath}/media/ppa-studio-scene.webp`} alt="Prime Presence Atelier digital environment" fill priority sizes="100vw" className="object-cover object-center"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(2,2,2,.94)_0%,rgba(2,2,2,.68)_48%,rgba(2,2,2,.22)_100%),linear-gradient(0deg,rgba(0,0,0,.72),transparent_55%)]"/><div className="relative mx-auto flex min-h-[720px] max-w-[1380px] items-end px-5 py-14 sm:min-h-[780px] sm:px-8 sm:py-20 lg:items-center lg:px-12"><div className="max-w-[700px]"><div className="inline-flex items-center gap-3 border border-[#c99a3c]/35 bg-black/45 px-3.5 py-2 backdrop-blur"><span className="h-1.5 w-1.5 rounded-full bg-[#dfb75d] shadow-[0_0_16px_rgba(223,183,93,.72)]"/><span className="text-[8px] font-bold uppercase tracking-[.22em] text-[#dfb75d]">Private preview · Coming soon</span></div><p className="mt-8 text-[9px] font-bold uppercase tracking-[.25em] text-white/45">Prime Presence Connect™</p><h2 className="mt-5 max-w-[9ch] font-[family-name:var(--font-cormorant)] text-[clamp(3.7rem,10vw,7.5rem)] font-medium leading-[.8] tracking-[-.045em] text-[#f7f0e5]">The moment after <span className="italic text-[#d7aa4f]">hello.</span></h2><p className="mt-7 max-w-lg text-[15px] leading-7 text-white/65 sm:text-lg sm:leading-8">Someone asks who you are. What you do. How to reach you. What happens next should feel as considered as the introduction itself.</p><a href="#clues" className="mt-9 inline-flex min-h-12 items-center gap-5 border-b border-[#d6aa51]/55 text-[9px] font-bold uppercase tracking-[.18em] text-[#e0b75f]">Reveal the clues <span>↓</span></a></div></div></div></section>
<section id="clues" className="mt-20 scroll-mt-24 sm:mt-28"><div className="grid gap-10 lg:grid-cols-[.48fr_1.52fr] lg:gap-20"><div><p className="eyebrow">Three clues</p><h2 className="section-title mt-4">We can tell you this much.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-white/42">Tap each clue. The finished product remains under wraps; the intent does not.</p></div><div className="grid gap-4 md:grid-cols-3">{clues.map(([number,title,body],i)=><article key={number} tabIndex={0} className="group relative min-h-[390px] overflow-hidden border border-white/[.09] bg-[#080706] outline-none transition duration-500 hover:-translate-y-1 hover:border-[#c99a3c]/45 focus-visible:-translate-y-1 focus-visible:border-[#c99a3c]/60"><Image src={`${basePath}${i===0?"/media/ppa-brand-identity-1.webp":i===1?"/media/ppa-studio-scene.webp":"/media/ppa-hero-collateral.webp"}`} alt="" fill sizes="(max-width:768px) 100vw,33vw" className="object-cover opacity-45 transition duration-700 group-hover:scale-105 group-hover:opacity-70 group-focus-visible:scale-105 group-focus-visible:opacity-70"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/55 to-black/10"/><div className="absolute inset-x-0 bottom-0 p-6"><p className="text-[9px] font-bold tracking-[.2em] text-[#c99a3c]">{number}</p><h3 className="mt-5 font-[family-name:var(--font-cormorant)] text-4xl italic text-[#f1e9dd]">{title}.</h3><p className="mt-4 text-sm leading-7 text-white/58">{body}</p><p className="mt-5 text-[8px] font-bold uppercase tracking-[.18em] text-[#dcb25b]">Touch / hover</p></div></article>)}</div></div></section>
<section className="relative mt-20 min-h-[620px] overflow-hidden border border-[#c99a3c]/16 sm:mt-28"><Image src={`${basePath}/media/ppa-hero-collateral.webp`} alt="Prime Presence Atelier collateral and presentation system" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,3,2,.93)_0%,rgba(4,3,2,.68)_56%,rgba(4,3,2,.18)_100%)]"/><div className="relative flex min-h-[620px] items-center p-7 sm:p-10 lg:p-14"><div className="max-w-[650px]"><p className="text-[8px] font-bold uppercase tracking-[.25em] text-[#d5a94f]">Prime Presence Connect™</p><h2 className="mt-6 font-[family-name:var(--font-cormorant)] text-[clamp(3rem,7vw,6rem)] font-medium leading-[.86] tracking-[-.04em] text-[#f4ede2]">The introduction is <span className="italic text-[#d8ac52]">changing.</span></h2><p className="mt-6 max-w-xl text-sm leading-7 text-white/55 sm:text-base">No launch date. No unfinished demo. We will reveal Connect when it is ready to carry the Prime Presence name.</p><div className="mt-8 inline-flex items-center gap-3 border border-[#c99a3c]/35 bg-black/35 px-4 py-2.5 backdrop-blur"><span className="h-1.5 w-1.5 rounded-full bg-[#d9ae55]"/><span className="text-[8px] font-bold uppercase tracking-[.22em] text-[#ddb45b]">Coming Soon</span></div></div></div></section>
<section className="mt-16 sm:mt-20"><div className="flex flex-col gap-6 border-t border-white/[.08] pt-8 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">While we build</p><h2 className="mt-3 font-[family-name:var(--font-cormorant)] text-3xl text-[#f3ece2] sm:text-4xl">The Atelier is open.</h2></div><Link href="/services" className="button-primary shrink-0">Explore Current Services</Link></div></section>
</PageShell>}
