import Image from "next/image";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import Contact from "@/components/Contact";
import { services } from "@/content/services";
import { contactDetails } from "@/content/site";

const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
export const metadata={title:"The Prime Presence System",description:"Identity, digital presence and launch services shaped as one coherent perception system by Prime Presence Atelier.",alternates:{canonical:"/services"}};
const imagery=["/media/ppa-brand-identity-1.webp","/media/ppa-studio-scene.webp","/media/ppa-hero-collateral.webp","/media/ppa-brand-identity-1.webp","/media/ppa-studio-scene.webp"] as const;
const system=[["01","Identity","Recognise"],["02","Digital Presence","Trust"],["03","Launch","Enter"],["04","Connect™","Continue"]] as const;

export default function Page(){return <PageShell after={<Contact contact={contactDetails}/>} eyebrow="The Prime Presence System" title="One business. One impression." intro="Your customer does not experience a logo, website and launch campaign as separate purchases. They experience one business. We shape the visible system around that reality.">
<section className="relative mb-16 overflow-hidden border border-[#C8A348]/20 bg-[#080706] shadow-[0_35px_100px_rgba(0,0,0,.45)]"><div className="grid lg:grid-cols-[1.18fr_.82fr]"><div className="relative min-h-[480px] sm:min-h-[600px]"><Image src={`${basePath}/media/ppa-brand-identity-1.webp`} alt="Prime Presence Atelier identity system" fill priority sizes="(max-width:1024px) 100vw,60vw" className="object-cover object-center transition duration-1000 hover:scale-[1.02]"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(0,0,0,.66),transparent_60%)]"/><div className="absolute bottom-6 left-6 right-6 flex items-end justify-between border-t border-white/25 pt-4"><div><p className="text-[8px] font-bold uppercase tracking-[.22em] text-[#d7ad55]">Owned proof / Identity</p><p className="mt-2 font-[family-name:var(--font-cormorant)] text-2xl text-white sm:text-3xl">A system people can recognise.</p></div><span className="hidden text-3xl text-[#d7ad55] sm:block">↘</span></div></div><div className="flex items-center p-7 sm:p-10 lg:p-12"><div><p className="eyebrow">The architecture</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-5xl leading-[.88] text-white sm:text-7xl">Recognise.<br/><span className="italic text-[#d5aa52]">Trust.</span><br/>Remember.</h2><p className="mt-7 max-w-md text-[15px] leading-8 text-white/55">Every layer has a different job, but every layer should reinforce the same intended perception.</p><a href="#services-system" className="mt-8 inline-flex min-h-11 items-center gap-5 border-b border-[#c99a3c]/55 text-[9px] font-bold uppercase tracking-[.17em] text-[#e0b75f]">Enter the system <span>↓</span></a></div></div></div></section>

<section className="mb-16 border-y border-white/[.08]"><div className="grid sm:grid-cols-4">{system.map(([n,t,o],i)=><a key={n} href="#services-system" className={`group relative min-h-[170px] p-5 transition duration-300 hover:bg-white/[.035] focus-visible:bg-white/[.035] sm:min-h-[210px] sm:p-6 ${i?'border-t sm:border-l sm:border-t-0':''} border-white/[.08]`}><p className="text-[8px] font-bold tracking-[.2em] text-[#c99a3c]">{n}</p><p className="mt-7 font-[family-name:var(--font-cormorant)] text-2xl text-white transition group-hover:text-[#e3bd69] sm:text-3xl">{t}</p><p className="mt-3 text-[9px] font-bold uppercase tracking-[.18em] text-white/34">{o}</p><span className="absolute bottom-5 right-5 text-[#c99a3c] transition group-hover:translate-x-1">→</span></a>)}</div></section>

<div id="services-system" className="scroll-mt-24 space-y-6">{services.map((service,index)=><article key={service.slug} className="group overflow-hidden border border-white/[.08] bg-[#070706]"><div className={`grid lg:grid-cols-[1.08fr_.92fr] ${index%2?'lg:[&>*:first-child]:order-2':''}`}><Link href={service.slug==="connect"?"/connect":"/contact"} className="relative block min-h-[440px] overflow-hidden sm:min-h-[560px]"><Image src={`${basePath}${imagery[index]||imagery[0]}`} alt={`${service.title} visual study by Prime Presence Atelier`} fill sizes="(max-width:1024px) 100vw,55vw" className="object-cover transition duration-700 ease-out group-hover:scale-[1.035] group-focus-within:scale-[1.035]"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.05)_25%,rgba(0,0,0,.78)_100%)]"/><div className="absolute inset-x-0 bottom-0 p-6 sm:p-8"><div className="flex items-center justify-between border-t border-white/25 pt-4"><p className="text-[8px] font-bold uppercase tracking-[.22em] text-[#e0b45b]">System / 0{index+1}</p><span className="grid size-11 place-items-center rounded-full border border-[#d7aa50]/55 text-[#e6bd68] transition duration-300 group-hover:translate-x-1">→</span></div><p className="mt-4 text-[8px] font-bold uppercase tracking-[.18em] text-white/55">Tap to explore</p></div></Link><div className="flex min-h-[410px] items-center p-7 sm:p-10 lg:p-12"><div className="max-w-xl"><p className="eyebrow">Perception layer</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-4xl leading-[.95] text-[#f3ece1] sm:text-6xl">{service.title}</h2>{service.slug==="connect"&&<span className="mt-4 inline-block border border-[#c99a3c]/28 px-3 py-1.5 text-[8px] font-bold uppercase tracking-[.18em] text-[#d8ae55]">Coming Soon</span>}<p className="mt-6 text-[15px] leading-8 text-white/58">{service.summary}</p><div className="mt-7 border-t border-white/[.08] pt-5"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-[#c99a3c]">What this layer creates</p><p className="mt-3 text-sm leading-7 text-white/42">{service.deliverables}</p></div><Link href={service.slug==="connect"?"/connect":"/contact"} className="mt-7 inline-flex min-h-11 items-center gap-5 border-b border-[#c99a3c]/55 text-[9px] font-bold uppercase tracking-[.17em] text-[#e0b75f]">{service.slug==="connect"?"Enter the Preview":"Discuss the Direction"} <span>→</span></Link></div></div></div></article>)}</div>

<section className="relative mt-16 min-h-[650px] overflow-hidden border border-[#c99a3c]/16"><Image src={`${basePath}/media/ppa-hero-collateral.webp`} alt="Prime Presence Atelier delivery and presentation system" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(3,3,2,.94)_0%,rgba(3,3,2,.72)_54%,rgba(3,3,2,.2)_100%)]"/><div className="relative flex min-h-[650px] items-center p-7 sm:p-10 lg:p-14"><div className="max-w-[680px]"><p className="eyebrow">Built deliberately</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(3.2rem,7vw,6.5rem)] leading-[.86] tracking-[-.04em] text-white">One direction.<br/><span className="italic text-[#d6aa52]">Controlled scope.</span><br/>Clear approval.</h2><p className="mt-7 max-w-xl text-[15px] leading-8 text-white/58">Founder-led direction keeps the standard close to the work. Technology accelerates research, production and QA where useful; human judgement remains responsible for what reaches the client and the market.</p><Link href="/process" className="mt-8 inline-flex min-h-11 items-center gap-5 border-b border-[#c99a3c]/55 text-[9px] font-bold uppercase tracking-[.17em] text-[#e0b75f]">See How It Is Built <span>→</span></Link></div></div></section>
</PageShell>}
