import Image from "next/image";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import ProjectShowcase from "@/components/portfolio/ProjectShowcase";
import {publishedProjects} from "@/content/projects";
const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
export const metadata={title:"Work · The Presence Archive",description:"Owned proof, approved client work and product development from Prime Presence Atelier.",alternates:{canonical:"/work"}};
const layers=[["01","Identity","Recognise","/media/ppa-brand-identity-1.webp"],["02","Digital","Trust","/media/ppa-studio-scene.webp"],["03","Launch","Enter","/media/ppa-hero-collateral.webp"],["04","Connect™","Continue","/media/ppa-studio-scene.webp"]] as const;
export default function Page(){return <PageShell eyebrow="Work · The Presence Archive" title="See the system, not just the asset." intro="The strongest proof is not a beautiful object in isolation. It is the same intention surviving across every place the business is encountered.">
<section className="relative -mx-5 min-h-[760px] overflow-hidden border-y border-white/[.07] sm:-mx-8 lg:-mx-12"><Image src={`${basePath}/media/ppa-hero-collateral.webp`} alt="Prime Presence Atelier owned identity and collateral system" fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(3,3,2,.94),rgba(3,3,2,.62)_55%,rgba(3,3,2,.15)),linear-gradient(0deg,rgba(0,0,0,.5),transparent_60%)]"/><div className="relative mx-auto flex min-h-[760px] max-w-[1380px] items-center px-5 py-16 sm:px-8 lg:px-12"><div className="max-w-[720px]"><p className="eyebrow">Owned proof / 001</p><h2 className="mt-6 max-w-[10ch] font-[family-name:var(--font-cormorant)] text-[clamp(3.5rem,8vw,7rem)] leading-[.84] tracking-[-.045em] text-[#f4ede2]">One idea.<br/><span className="italic text-[#d6aa50]">Four encounters.</span></h2><p className="mt-7 max-w-md text-[15px] leading-8 text-white/52">Prime Presence Atelier itself is the first live study: an identity designed to remain recognisable as it moves through digital presence, launch and future product layers.</p><a href="#archive" className="mt-8 inline-flex min-h-11 items-center gap-5 border-b border-[#c99a3c]/55 text-[9px] font-bold uppercase tracking-[.17em] text-[#e0b75f]">Open the archive <span>↓</span></a></div></div></section>
<section id="archive" className="mt-20 scroll-mt-24 sm:mt-28"><div className="grid gap-4 lg:grid-cols-12">{layers.map(([n,t,o,img],i)=><Link key={n} href={i===3?"/connect":i===1?"/services":"/contact"} className={`${i===0?"lg:col-span-7 lg:row-span-2 min-h-[650px]":"lg:col-span-5 min-h-[380px]"} group relative isolate overflow-hidden border border-white/[.08]`}><Image src={`${basePath}${img}`} alt={`${t} visual study by Prime Presence Atelier`} fill sizes={i===0?"(max-width:1024px) 100vw,58vw":"(max-width:1024px) 100vw,42vw"} className="-z-20 object-cover transition duration-700 group-hover:scale-[1.035] group-focus-visible:scale-[1.035]"/><div className="absolute inset-0 -z-10 bg-gradient-to-t from-black via-black/35 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 sm:p-8"><div className="flex items-center justify-between border-t border-white/25 pt-4"><p className="text-[8px] font-bold tracking-[.2em] text-[#d9ae55]">{n}</p><span className="grid size-10 place-items-center rounded-full border border-[#d7aa50]/55 text-[#e6bd68] transition group-hover:translate-x-1">→</span></div><h3 className="mt-4 font-[family-name:var(--font-cormorant)] text-4xl text-white sm:text-5xl">{t}</h3><p className="mt-2 text-[9px] font-bold uppercase tracking-[.18em] text-white/45">{o} · Tap to explore</p></div></Link>)}</div></section>
<section className="relative mt-20 min-h-[680px] overflow-hidden border border-white/[.08] sm:mt-28"><Image src={`${basePath}/media/ppa-brand-identity-1.webp`} alt="Prime Presence Atelier black and gold identity collateral" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(0deg,#050504_0%,rgba(5,5,4,.18)_60%,rgba(5,5,4,.03))]"/><div className="absolute inset-x-0 bottom-0 p-7 sm:p-12"><p className="eyebrow">Prime Presence Atelier · Owned system</p><h2 className="mt-4 max-w-[12ch] font-[family-name:var(--font-cormorant)] text-5xl leading-[.9] text-white sm:text-7xl">Designed to remain itself <span className="italic text-[#d6aa50]">everywhere.</span></h2></div></section>
{publishedProjects.length?<section className="mt-20 sm:mt-28"><div className="mb-8"><p className="eyebrow">Approved client work</p><h2 className="mt-4 font-[family-name:var(--font-cormorant)] text-4xl text-white">Published with permission.</h2></div><ProjectShowcase projects={publishedProjects}/></section>:<section className="relative mt-20 min-h-[620px] overflow-hidden border border-white/[.08] sm:mt-28"><Image src={`${basePath}/media/ppa-studio-scene.webp`} alt="Prime Presence Atelier studio scene" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,3,2,.94),rgba(4,3,2,.67)_58%,rgba(4,3,2,.14))]"/><div className="relative flex min-h-[620px] items-center p-7 sm:p-10 lg:p-14"><div className="max-w-[690px]"><p className="eyebrow">Proof policy</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(3rem,6vw,5.5rem)] leading-[.88] text-[#f2eadf]">No borrowed credibility.<br/><span className="italic text-[#d5a94f]">No invented success.</span></h2><p className="mt-6 max-w-xl text-sm leading-7 text-white/48">Client work enters the archive only when we have permission to publish it. Until then, owned work and clearly labelled product development carry the proof.</p><Link href="/contact" className="button-primary mt-8">Shape Your Presence</Link></div></div></section>}
</PageShell>}
