import Image from "next/image";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import ProjectShowcase from "@/components/portfolio/ProjectShowcase";
import AtelierVisual from "@/components/AtelierVisual";
import { publishedProjects } from "@/content/projects";

const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
export const metadata={title:"Work · The Presence Archive",description:"Owned proof, approved client work and product development from Prime Presence Atelier.",alternates:{canonical:"/work"}};
const layers=[["01","Identity","Recognise"],["02","Digital","Trust"],["03","Launch","Enter"],["04","Connect™","Continue"]] as const;

export default function Page(){return <PageShell eyebrow="Work · The Presence Archive" title="See the system, not just the asset." intro="The strongest proof is not a beautiful object in isolation. It is the same intention surviving across every place the business is encountered.">
<section className="relative -mx-5 overflow-hidden border-y border-white/[.07] bg-[#050504] px-5 py-16 sm:-mx-8 sm:px-8 sm:py-24 lg:-mx-12 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1180px] gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-center lg:gap-20"><div><p className="eyebrow">Owned proof / 001</p><h2 className="mt-6 max-w-[10ch] font-[family-name:var(--font-cormorant)] text-[clamp(3.3rem,7vw,6.5rem)] leading-[.86] tracking-[-.04em] text-[#f4ede2]">One idea.<br/><span className="italic text-[#d6aa50]">Four encounters.</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-white/44">Prime Presence Atelier itself is the first live study: an identity designed to remain recognisable as it moves through digital presence, launch and future product layers.</p></div><AtelierVisual variant="archive" label="Prime Presence system archive"/></div></section>

<section className="mt-20 sm:mt-28"><article className="group relative min-h-[560px] overflow-hidden border border-white/[.08] bg-[#080706] sm:min-h-[700px]"><Image src={`${basePath}/media/ppa-brand-identity-1.webp`} alt="Prime Presence Atelier black and gold identity collateral" fill priority sizes="100vw" className="object-cover transition-transform duration-1000 group-hover:scale-[1.012]"/><div className="absolute inset-0 bg-[linear-gradient(0deg,#050504_0%,rgba(5,5,4,.16)_58%,rgba(5,5,4,.02)_100%)]"/><div className="absolute inset-x-0 bottom-0 p-7 sm:p-12"><p className="eyebrow">Prime Presence Atelier · Owned system</p><h2 className="mt-4 max-w-[12ch] font-[family-name:var(--font-cormorant)] text-5xl leading-[.9] text-white sm:text-7xl">Designed to remain itself <span className="italic text-[#d6aa50]">everywhere.</span></h2></div></article>
<div className="grid border-x border-b border-white/[.08] sm:grid-cols-4">{layers.map(([n,t,o],i)=><div key={n} className={`min-h-[150px] p-5 sm:min-h-[185px] sm:p-6 ${i?'border-t sm:border-l sm:border-t-0':''} border-white/[.08]`}><p className="text-[8px] font-bold tracking-[.2em] text-[#c99a3c]">{n}</p><p className="mt-6 font-[family-name:var(--font-cormorant)] text-2xl text-[#f2eadf]">{t}</p><p className="mt-2 text-[8px] font-bold uppercase tracking-[.18em] text-white/32">{o}</p></div>)}</div></section>

<section className="mt-20 grid gap-5 sm:mt-28 lg:grid-cols-[1.2fr_.8fr]"><div className="border border-white/[.08] bg-[#070604] p-5 sm:p-7"><AtelierVisual variant="digital" label="Digital presence interface study"/><div className="px-2 pb-2 pt-7 sm:px-4"><p className="eyebrow">System / Digital Presence</p><h2 className="mt-4 font-[family-name:var(--font-cormorant)] text-4xl text-white sm:text-5xl">Recognition becomes experience.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-white/45">The website is not treated as a separate design exercise. Typography, hierarchy, interaction and enquiry paths inherit the same intended perception.</p></div></div><div className="border border-[#c99a3c]/16 bg-[#070604] p-5 sm:p-7"><AtelierVisual variant="connect" label="Prime Presence Connect concept preview"/><div className="px-2 pb-2 pt-7 sm:px-4"><span className="inline-flex border border-[#c99a3c]/28 px-3 py-2 text-[8px] font-bold uppercase tracking-[.2em] text-[#d7ac53]">Coming Soon</span><p className="eyebrow mt-6">System / Connect™</p><h2 className="mt-4 font-[family-name:var(--font-cormorant)] text-4xl leading-[.92] text-white">The presence continues after hello.</h2><Link href="/connect" className="mt-6 inline-flex min-h-10 items-center gap-4 border-b border-[#c99a3c]/50 text-[9px] font-bold uppercase tracking-[.17em] text-[#deb45a]">Enter the preview <span>→</span></Link></div></div></section>

{publishedProjects.length?<section className="mt-20 sm:mt-28"><div className="mb-8"><p className="eyebrow">Approved client work</p><h2 className="mt-4 font-[family-name:var(--font-cormorant)] text-4xl text-white">Published with permission.</h2></div><ProjectShowcase projects={publishedProjects}/></section>:<section className="mt-20 grid gap-5 sm:mt-28 lg:grid-cols-[1.05fr_.95fr]"><AtelierVisual variant="identity" label="Prime Presence identity study"/><div className="flex items-center border border-white/[.08] bg-[#070604] p-7 sm:p-10"><div><p className="eyebrow">Proof policy</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(2.8rem,6vw,5rem)] leading-[.9] text-[#f2eadf]">No borrowed credibility.<br/><span className="italic text-[#d5a94f]">No invented success.</span></h2><p className="mt-6 max-w-xl text-sm leading-7 text-white/42">Client work enters the archive only when we have permission to publish it. Until then, owned work and clearly labelled product development carry the proof.</p><Link href="/contact" className="button-primary mt-8">Shape Your Presence</Link></div></div></section>}
</PageShell>}
