import type {Metadata} from "next";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Contact from "@/components/Contact";
import SocialPresence from "@/components/SocialPresence";
import {contactDetails,site} from "@/content/site";
const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
export const metadata:Metadata={title:"Start a Project",description:"Discuss an identity, digital presence or launch project with Prime Presence Atelier.",alternates:{canonical:"/contact"}};
const fit=[["01","The business has moved","The current presence no longer reflects the level, direction or ambition of the business."],["02","Something important is launching","A new company, offer, identity or digital experience needs a coherent first public impression."],["03","The pieces do not feel connected","The identity, website and launch touchpoints exist, but they do not communicate one deliberate business." ]] as const;
export default function Page(){return <><Navbar siteName={site.name}/><main id="main-content" className="pt-20">
<section className="px-4 pt-8 sm:px-8 sm:pt-12 lg:px-12"><div className="mx-auto grid max-w-[1380px] overflow-hidden border border-white/[.08] bg-[#070604] lg:grid-cols-[1.08fr_.92fr]"><div className="relative min-h-[390px] overflow-hidden sm:min-h-[500px] lg:min-h-[610px]"><Image src={`${basePath}/media/ppa-brand-identity-1.webp`} alt="Prime Presence Atelier identity system" fill priority sizes="(max-width:1024px) 100vw,55vw" className="object-cover object-center"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(0,0,0,.68),transparent_58%),linear-gradient(90deg,transparent_52%,rgba(7,6,4,.5))]"/><div className="absolute bottom-7 left-6 right-6 sm:bottom-10 sm:left-10"><p className="text-[8px] font-bold uppercase tracking-[.22em] text-[#d6ad58]">Project entry · Not a sales funnel</p><p className="mt-4 max-w-[10ch] font-[family-name:var(--font-cormorant)] text-4xl leading-[.9] text-[#f3ece1] sm:text-6xl">Start with what should feel <span className="italic text-[#d5aa52]">different.</span></p></div></div><div className="flex items-center p-7 sm:p-10 lg:p-12"><div><p className="eyebrow">Shape your presence</p><h1 className="mt-5 max-w-[10ch] font-[family-name:var(--font-cormorant)] text-[clamp(3.1rem,6vw,5.5rem)] leading-[.87] tracking-[-.04em] text-[#f4ede2]">You do not need to know what to <span className="italic text-[#d5aa52]">buy.</span></h1><p className="mt-6 max-w-xl text-[15px] leading-8 text-white/52">Tell us what the business is becoming, what currently feels misaligned and what needs to happen next. We will determine whether Identity, Digital Presence, Launch—or a focused combination—is the right scope.</p><div className="mt-8 grid grid-cols-3 gap-3 border-t border-white/[.08] pt-6">{[["01","Context"],["02","Fit"],["03","Direction"]].map(([n,t])=><div key={n}><p className="text-[8px] font-bold tracking-[.18em] text-[#c99a3c]">{n}</p><p className="mt-2 font-[family-name:var(--font-cormorant)] text-xl text-[#eee6da] sm:text-2xl">{t}</p></div>)}</div></div></div></div></section>
<section className="px-4 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto max-w-[1380px]"><div className="grid gap-10 lg:grid-cols-[.5fr_1.5fr] lg:gap-20"><div><p className="eyebrow">Good reasons to begin</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(2.8rem,5vw,4.8rem)] leading-[.9] text-white">When the old impression is holding back the next <span className="italic text-[#d5a94f]">chapter.</span></h2></div><div className="grid gap-px bg-white/[.08] md:grid-cols-3">{fit.map(([n,t,b])=><article key={n} className="min-h-[260px] bg-[#070604] p-6 sm:p-7"><p className="text-[8px] font-bold tracking-[.2em] text-[#c99a3c]">{n}</p><h3 className="mt-9 font-[family-name:var(--font-cormorant)] text-3xl leading-[.95] text-[#f2eadf]">{t}.</h3><p className="mt-5 text-sm leading-7 text-white/44">{b}</p></article>)}</div></div></div></section>
<section className="border-y border-white/[.07] bg-[#060504] px-4 py-14 sm:px-8 sm:py-18 lg:px-12"><div className="mx-auto grid max-w-[1380px] gap-8 sm:grid-cols-3">{[["No forced package","The brief determines the scope, not a preselected bundle."],["No invented urgency","Timing is discussed against the real launch, business and production constraints."],["No hidden theatre","Fit, exclusions, approval points and what happens next are made explicit before commencement."]].map(([t,b])=><div key={t} className="border-l border-[#c99a3c]/28 pl-5"><p className="font-[family-name:var(--font-cormorant)] text-2xl text-[#eee6da]">{t}</p><p className="mt-3 text-sm leading-7 text-white/40">{b}</p></div>)}</div></section>
<SocialPresence compact/>
<Contact contact={contactDetails} headingLevel="h2"/>
</main><Footer/></>}
