import test from "node:test"; import assert from "node:assert/strict";
import { validateOwnerContent } from "../lib/content-validation.mjs";
import { evaluateLaunchReadiness, evaluatePrivatePreviewReadiness } from "../lib/launch-readiness.mjs";

const complete = () => ({ business: { publicName:"Prime Presence",legalName:"Owner Entity",email:"owner@example.test",telephone:"+27111234567",whatsapp:"27111234567",location:"South Africa",serviceArea:"Owner supplied",hours:"09:00–17:00",socialLinks:[{label:"Network",url:"https://example.test/profile"}],copyrightHolder:"Owner Entity",legalContact:"legal@example.test",privacyContact:"privacy@example.test",termsContact:"legal@example.test",domain:"example.test",canonicalUrl:"https://example.test",ownerConfirmed:true,approvalDate:"2026-08-04" }, brand:{tagline:"Owner supplied",description:"Owner supplied"}, founders:[],team:[],testimonials:[],projects:[],media:[],legal:{privacyApproval:true,termsApproval:true,cookiePolicyRequired:false,analyticsPolicyApproved:true,legalReviewer:"Owner reviewer",approvalDate:"2026-08-04",outstandingIssues:[],mediaUseWordingApproved:true,clientPublicationWordingApproved:true},openGraph:{defaultArtwork:{src:"/images/social/default.webp",filename:"default.webp",alt:"Prime Presence social preview",width:1200,height:630,bytes:200000,publicationStatus:"published",approvalDate:"2026-08-04"},routeArtwork:[],projectArtwork:[]},verification:{domainValidated:true,realDeviceSignoff:true,lighthouseVerified:true,productionBuildPassed:true,routeChecksPassed:true,accessibilityCriticalChecksPassed:true,contactFlowPassed:true,highSeveritySecurityIssuesResolved:true,launchApprovalRecorded:true} });
test("complete manifest validates", () => assert.deepEqual(validateOwnerContent(complete(), { assetExists: () => true }), []));
test("duplicate slugs and filenames are reported clearly", () => { const data=complete(); const base={clientName:"Owner",services:[],summary:"Summary",publicationStatus:"draft",approvalDate:null,mediaRightsConfirmed:false,clientPublicationApproved:false,publicationDate:null}; data.projects=[{...base,slug:"same",gallery:[{src:"/a.webp",filename:"same.webp",alt:"A",width:1,height:1}]},{...base,slug:"same",gallery:[{src:"/b.webp",filename:"same.webp",alt:"B",width:1,height:1}]}]; const codes=validateOwnerContent(data).map(item=>item.code); assert.ok(codes.includes("duplicate_slug")); assert.ok(codes.includes("duplicate_filename")); });
test("published project without media, rights and approval is blocked", () => { const data=complete(); data.projects=[{slug:"unsafe",clientName:"Owner",services:[],summary:"Summary",publicationStatus:"published",approvalDate:"2026-08-04",mediaRightsConfirmed:false,clientPublicationApproved:false,publicationDate:"2026-08-04"}]; const codes=validateOwnerContent(data).map(item=>item.code); assert.ok(codes.includes("project_publication_blocked")); assert.ok(codes.includes("missing_case_study_evidence")); });
test("invalid contact, social URL and missing video poster are detected", () => { const data=complete(); data.business.email="not-email"; data.business.socialLinks=[{label:"Bad",url:"javascript:alert(1)"}]; data.projects=[{slug:"draft",clientName:"Owner",services:[],summary:"Summary",publicationStatus:"draft",approvalDate:null,mediaRightsConfirmed:false,clientPublicationApproved:false,publicationDate:null,brandRevealVideo:{src:"/clip.mp4",poster:"",filename:"clip.mp4",posterFilename:"",label:"Clip"}}]; const codes=validateOwnerContent(data).map(item=>item.code); assert.ok(codes.includes("invalid_email")); assert.ok(codes.includes("invalid_social_url")); assert.ok(codes.includes("missing_video_poster")); });
test("launch evaluator never invents a readiness score", () => { const data=complete(); data.verification.realDeviceSignoff=false; const result=evaluateLaunchReadiness(data,{assetExists:()=>true}); assert.equal(result.ready,false); assert.equal(result.gates.find(g=>g.code==="real_device")?.passed,false); });
test("public launch requires explicit switch and recorded approval",()=>{const data=complete();data.verification.launchApprovalRecorded=false;assert.equal(evaluateLaunchReadiness(data,{assetExists:()=>true,publicLaunchApproved:true}).ready,false);data.verification.launchApprovalRecorded=true;assert.equal(evaluateLaunchReadiness(data,{assetExists:()=>true,publicLaunchApproved:false}).ready,false)});
test("private preview ignores owner launch omissions but requires explicit preview mode",()=>{const data=complete();data.business.legalName="";assert.equal(evaluatePrivatePreviewReadiness(data,{assetExists:()=>true,previewEnabled:false}).ready,false);assert.equal(evaluatePrivatePreviewReadiness(data,{assetExists:()=>true,previewEnabled:true}).ready,true)});
test("published Open Graph artwork enforces dimensions, format and size",()=>{const data=complete();data.openGraph.defaultArtwork={...data.openGraph.defaultArtwork,width:1000,filename:"bad.png",src:"/bad.png",bytes:400000};const codes=validateOwnerContent(data).map(item=>item.code);assert.ok(codes.includes("invalid_og_dimensions"));assert.ok(codes.includes("invalid_og_format"));assert.ok(codes.includes("invalid_og_size"))});
