import Image from "next/image";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import ProofSection from "@/components/ProofSection";

const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
const principles=[["01","Perception before decoration","The question is not whether something looks expensive. It is what the business should communicate before anyone speaks to it."],["02","Evidence before theatre","No invented clients, outcomes, awards, offices or capabilities. Real work is labelled precisely and proof grows with the business."],["03","Restraint before noise","Every element must earn its place. Motion, typography, imagery and technology exist to improve hierarchy, meaning or experience—not to demonstrate technique."],["04","Verification before release","A polished presentation is not enough. Digital work has to survive real devices, browsers, interaction, accessibility and the final production endpoint."]] as const;
const model=[["Founder-led","The person accountable for the standard remains close to direction, decisions and final approval."],["Controlled capacity","The Atelier does not need to imitate a large agency. Scope and workload are kept deliberate so quality does not become theatre."],["Technology assisted","AI and automation may accelerate research, production and QA. They do not replace judgement, taste, truth or approval."],["System minded","Identity, digital presence and launch are designed as connected encounters with one business, not unrelated purchases."]] as const;
export const metadata={title:"About · The Atelier",description:"Prime Presence Atelier is a founder-led creative atelier shaping how businesses are perceived through identity, digital presence and disciplined execution.",alternates:{canonical:"/about"}};

export default function Page(){return <PageShell eyebrow="About · The Atelier" title="Small by design. Serious by standard." intro="Prime Presence Atelier is built around a simple belief: a business does not need to pretend to be larger than it is. It needs a presence credible enough for where it intends to go next.">
<section className="relative -mx-5 overflow-hidden border-y border-white/[.07] bg-[#050504] px-5 py-16 sm:-mx-8 sm:px-8 sm:py-24 lg:-mx-12 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1180px] gap-12 lg:grid-cols-[.78fr_1.22fr] lg:items-center lg:gap-20"><div><p className="eyebrow">Why we exist</p><h2 className="mt-6 max-w-[10ch] font-[family-name:var(--font-cormorant)] text-[clamp(3.2rem,7vw,6.4rem)] font-medium leading-[.86] tracking-[-.04em] text-[#f4ede2]">We design how a business is <span className="italic text-[#d6aa50]">perceived.</span></h2><p className="mt-7 max-w-xl text-[15px] leading-8 text-white/52">Not only its logo. Not only its website. The identity, digital experience and launch touchpoints are treated as one perception system because that is how the customer encounters them.</p><Link href="/services" className="mt-7 inline-flex min-h-11 items-center gap-5 border-b border-[#c99a3c]/55 text-[9px] font-bold uppercase tracking-[.17em] text-[#e0b75f]">See the Presence System <span>→</span></Link></div><div className="relative min-h-[520px] sm:min-h-[620px]"><figure className="absolute inset-x-0 top-0 overflow-hidden border border-white/[.08] bg-[#090806] shadow-[0_35px_100px_rgba(0,0,0,.5)] sm:left-10"><Image src={`${basePath}/media/ppa-brand-identity-1.webp`} alt="Prime Presence Atelier black and gold identity collateral" width={1536} height={1024} className="aspect-[4/3] w-full object-cover object-center transition duration-1000 hover:scale-[1.025]" priority/><div className="absolute inset-0 bg-[linear-gradient(180deg,transparent_58%,rgba(0,0,0,.55))]"/><figcaption className="absolute bottom-5 left-5 border-l border-[#c99a3c]/60 pl-4 text-[8px] font-bold uppercase tracking-[.2em] text-[#ddba68]">Owned proof · Prime Presence identity system</figcaption></figure><div className="absolute bottom-0 left-0 w-[76%] border border-[#c99a3c]/20 bg-[#080706]/95 p-6 shadow-[0_25px_70px_rgba(0,0,0,.55)] backdrop-blur sm:w-[60%] sm:p-7"><p className="text-[8px] font-bold uppercase tracking-[.22em] text-[#c99a3c]">Atelier note / 01</p><p className="mt-4 font-[family-name:var(--font-cormorant)] text-3xl leading-[.95] text-[#f0e8dc] sm:text-4xl">The impression arrives before the conversation.</p><p className="mt-4 text-sm leading-7 text-white/45">That first encounter deserves the same seriousness as the work behind the business.</p></div></div></div></section>

<section className="mt-20 sm:mt-28"><div className="grid gap-10 lg:grid-cols-[.48fr_1.52fr] lg:gap-20"><div><p className="eyebrow">The operating model</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(2.9rem,5vw,4.8rem)] leading-[.9] text-white">Not an agency costume.<br/><span className="italic text-[#d5a94f]">An Atelier system.</span></h2><p className="mt-6 max-w-sm text-sm leading-7 text-white/42">The structure is intentionally lean. The standard is not.</p></div><div className="grid gap-px bg-white/[.08] sm:grid-cols-2">{model.map(([t,b],i)=><article key={t} tabIndex={0} className="group min-h-[230px] bg-[#070604] p-6 outline-none transition duration-300 hover:bg-[#0d0a06] focus-visible:bg-[#0d0a06] sm:p-7"><div className="flex items-center justify-between"><p className="text-[8px] font-bold tracking-[.2em] text-[#c99a3c]">0{i+1}</p><span className="text-[#c99a3c]/45 transition group-hover:rotate-45 group-hover:text-[#dcb35c] group-focus-visible:rotate-45">+</span></div><h3 className="mt-8 font-[family-name:var(--font-cormorant)] text-3xl text-[#f2eadf] transition group-hover:text-[#e3bd69]">{t}.</h3><p className="mt-4 text-sm leading-7 text-white/44">{b}</p><p className="mt-5 text-[8px] font-bold uppercase tracking-[.18em] text-white/25 transition group-hover:text-[#c99a3c]">Touch / hover</p></article>)}</div></div></section>

<section className="mt-20 overflow-hidden border border-[#c99a3c]/16 bg-[#070604] sm:mt-28"><div className="grid lg:grid-cols-[1.08fr_.92fr]"><Link href="/work" className="group relative block min-h-[500px] overflow-hidden sm:min-h-[650px]"><Image src={`${basePath}/media/ppa-brand-identity-1.webp`} alt="Prime Presence Atelier identity study" fill sizes="(max-width:1024px) 100vw,55vw" className="object-cover transition duration-700 ease-out group-hover:scale-[1.035] group-focus-visible:scale-[1.035]"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.04)_30%,rgba(0,0,0,.78)_100%)]"/><div className="absolute inset-x-0 bottom-0 p-6 sm:p-8"><div className="flex items-center justify-between border-t border-white/25 pt-4"><p className="text-[8px] font-bold uppercase tracking-[.22em] text-[#e0b45b]">Owned proof / Identity system</p><span className="grid size-11 place-items-center rounded-full border border-[#d7aa50]/55 text-[#e6bd68] transition duration-300 group-hover:translate-x-1">→</span></div><p className="mt-4 font-[family-name:var(--font-cormorant)] text-3xl text-white sm:text-4xl">Enter the work.</p><p className="mt-3 text-[8px] font-bold uppercase tracking-[.18em] text-white/45">Tap to explore</p></div></Link><div className="flex items-center p-7 sm:p-10 lg:p-12"><div><p className="eyebrow">What makes the standard different</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(2.9rem,5.5vw,5rem)] leading-[.9] text-white">The work must survive <span className="italic text-[#d5a94f]">scrutiny.</span></h2><p className="mt-6 max-w-xl text-[15px] leading-8 text-white/48">A concept is only the beginning. The final experience has to remain coherent when the screen narrows, the browser changes, the content becomes real and a customer tries to act.</p><Link href="/process" className="mt-7 inline-flex min-h-11 items-center gap-5 border-b border-[#c99a3c]/55 text-[9px] font-bold uppercase tracking-[.17em] text-[#e0b75f]">Enter the Process <span>→</span></Link></div></div></div></section>

<section className="mt-20 sm:mt-28"><div className="mb-10 max-w-3xl"><p className="eyebrow">Atelier code</p><h2 className="mt-5 font-[family-name:var(--font-cormorant)] text-[clamp(3rem,6vw,5.5rem)] leading-[.88] text-white">Four things we refuse to <span className="italic text-[#d5a94f]">compromise.</span></h2></div><div className="grid gap-px bg-white/[.08] sm:grid-cols-2 lg:grid-cols-4">{principles.map(([n,t,b])=><article key={n} tabIndex={0} className="group min-h-[310px] bg-[#070604] p-6 outline-none transition duration-300 hover:-translate-y-1 hover:bg-[#0c0905] focus-visible:-translate-y-1 focus-visible:bg-[#0c0905] sm:p-7"><p className="text-[9px] font-bold tracking-[.2em] text-[#c99a3c]">{n}</p><h3 className="mt-12 font-[family-name:var(--font-cormorant)] text-3xl leading-[.95] text-[#f0e8dc] transition group-hover:text-[#e2ba64]">{t}</h3><p className="mt-5 text-sm leading-7 text-white/44">{b}</p></article>)}</div></section>

<section className="relative mt-20 overflow-hidden border border-[#c99a3c]/16 bg-[#070604] sm:mt-28"><div className="grid lg:grid-cols-[1.05fr_.95fr]"><div className="relative min-h-[420px] overflow-hidden lg:min-h-[600px]"><Image src={`${basePath}/media/ppa-hero-collateral.webp`} alt="Prime Presence Atelier collateral and visual identity details" fill sizes="(max-width:1024px) 100vw,55vw" className="object-cover object-center transition duration-1000 hover:scale-[1.025]"/><div className="absolute inset-0 bg-[linear-gradient(90deg,transparent_40%,rgba(7,6,4,.72)_100%),linear-gradient(0deg,rgba(0,0,0,.35),transparent_55%)]"/></div><div className="flex items-center p-7 sm:p-10 lg:p-12"><div><p className="eyebrow">Founder-led by design</p><h2 className="mt-5 max-w-[11ch] font-[family-name:var(--font-cormorant)] text-[clamp(2.8rem,6vw,5.2rem)] leading-[.9] tracking-[-.035em] text-white">Fewer layers.<br/><span className="italic text-[#d5a94e]">More accountability.</span></h2><p className="mt-6 text-[15px] leading-8 text-white/52">The person responsible for the standard stays close to the work. Reusable systems stay behind the scenes; what reaches the market should still feel specific to the business in front of us.</p><Link href="/contact" className="button-primary mt-8">Discuss the Direction</Link></div></div></div></section>
<ProofSection/>
</PageShell>}
