"use client";
import { useState } from "react";
import { services } from "@/content/services";
import { buildWhatsAppUrl } from "@/lib/contact-url.mjs";
import { buildEnquiryMailto, validateEnquiry } from "@/lib/enquiry.mjs";

type Errors = Partial<Record<"name" | "email" | "details" | "consent", string>>;
type ContactDetails = { email: string; phoneDisplay: string; phoneInternational: string; contactReady: boolean; privacyApproved: boolean };
export default function Contact({ headingLevel = "h2", contact }: { headingLevel?: "h1" | "h2"; contact: ContactDetails }) {
  const [errors, setErrors] = useState<Errors>({});
  function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const input = { name: String(form.get("name") || ""), business: String(form.get("business") || ""), email: String(form.get("email") || ""), phone: String(form.get("phone") || ""), service: String(form.get("service") || ""), budget: String(form.get("budget") || ""), timeline: String(form.get("timeline") || ""), details: String(form.get("details") || ""), consent: form.get("consent") === "yes" }; const next: Errors = validateEnquiry(input);
    if (Object.keys(next).length) { setErrors(next); requestAnimationFrame(() => document.getElementById(`${Object.keys(next)[0]}-field`)?.focus()); return; }
    if (!contact.contactReady) { setErrors({ email: "The owner must confirm the public contact destination before enquiries can be sent." }); return; }
    setErrors({}); window.location.href = buildEnquiryMailto(contact.email, input);
  }
  const field = "mt-2 w-full min-w-0 rounded-[var(--radius-sm)] border border-white/15 bg-black/40 px-4 py-3 text-white transition-colors placeholder:text-white/35 hover:border-white/25 focus:border-[#C8A348]"; const Heading = headingLevel;
  return <section id="contact" className="section-space border-t border-white/10 bg-[#060606] px-4 sm:px-8"><div className="mx-auto grid min-w-0 max-w-7xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><div className="min-w-0"><p className="eyebrow">Start a project</p><Heading className="section-title mt-5 text-balance">Tell us what needs to become memorable.</Heading><p className="mt-6 leading-8 text-gray-300">Share the context, not a polished brief. Your answers prepare an email in your own mail app; nothing is silently submitted or stored.</p><div className="mt-8 border-l border-[#c8a348]/50 pl-5"><p className="text-sm font-semibold text-white">What happens next</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">Once you send the prepared email, we review fit, scope and timing before suggesting the clearest next step.</p></div><a className="link-arrow mt-7 inline-flex" href={buildWhatsAppUrl(contact.phoneInternational, "Hi Prime Presence, I'd like to discuss a project.")} target="_blank" rel="noreferrer">Prefer WhatsApp? {contact.phoneDisplay} <span aria-hidden="true">→</span></a></div>
  <form onSubmit={submit} noValidate className="grid min-w-0 gap-5 rounded-[var(--radius-lg)] border border-white/10 bg-[#0b0b0b] p-6 sm:grid-cols-2 sm:p-8" aria-label="Project enquiry">
    <Field label="Name" required error={errors.name}><input id="name-field" name="name" required autoComplete="name" className={field} aria-invalid={Boolean(errors.name)} aria-describedby={errors.name ? "name-error" : undefined} /></Field><Field label="Business name"><input name="business" autoComplete="organization" className={field} /></Field>
    <Field label="Email" required error={errors.email}><input id="email-field" name="email" required type="email" autoComplete="email" className={field} aria-invalid={Boolean(errors.email)} aria-describedby={errors.email ? "email-error" : undefined} /></Field><Field label="Telephone"><input name="phone" type="tel" autoComplete="tel" inputMode="tel" className={field} /></Field>
    <Field label="Service"><select name="service" className={field}>{services.map(service => <option key={service.slug}>{service.title}</option>)}</select></Field><Field label="Approximate budget"><select name="budget" className={field}><option>Not decided yet</option><option>R10,000–R25,000</option><option>R25,000–R50,000</option><option>R50,000+</option></select></Field>
    <Field label="Preferred timeline"><select name="timeline" className={field}><option>Flexible</option><option>Within 1 month</option><option>1–3 months</option><option>3+ months</option></select></Field><div className="hidden sm:block" aria-hidden="true" />
    <Field label="Project details" required error={errors.details} wide><textarea id="details-field" name="details" required minLength={20} className={`${field} min-h-40 resize-y`} aria-invalid={Boolean(errors.details)} aria-describedby={errors.details ? "details-error" : "details-help"} /><span id="details-help" className="mt-2 block text-xs text-[var(--muted)]">What are you building, changing, or preparing to launch?</span></Field>
    <div className="sm:col-span-2"><label className="flex items-start gap-3 text-sm leading-6 text-gray-300"><input id="consent-field" name="consent" value="yes" required type="checkbox" aria-invalid={Boolean(errors.consent)} aria-describedby={errors.consent ? "consent-error" : undefined} className="mt-1 h-5 w-5 shrink-0 accent-[#c8a348]" />I agree that Prime Presence may use these details to respond to my enquiry.</label>{contact.privacyApproved ? <a href="/privacy" className="ml-8 mt-2 inline-flex text-sm text-[#f0d788] underline underline-offset-4">Read the privacy policy</a> : <p className="ml-8 mt-2 text-sm text-amber-200">Privacy policy approval is pending; enquiry submission is disabled.</p>}{errors.consent && <p id="consent-error" className="mt-2 text-sm text-red-300">{errors.consent}</p>}</div>
    <button className="button-primary disabled:cursor-not-allowed disabled:opacity-50 sm:col-span-2" disabled={!contact.contactReady || !contact.privacyApproved} type="submit">Prepare enquiry email</button><p className="text-center text-xs leading-5 text-[var(--muted)] sm:col-span-2">You will review and send the message from your email application.</p>
  </form></div></section>;
}

function Field({ label, required, error, wide, children }: { label: string; required?: boolean; error?: string; wide?: boolean; children: React.ReactNode }) { const id = label === "Project details" ? "details" : label.toLowerCase().split(" ")[0]; return <label className={`min-w-0 ${wide ? "sm:col-span-2" : ""}`}><span className="text-sm font-medium text-gray-200">{label}{required && <span aria-hidden="true"> *</span>}</span>{children}{error && <span id={`${id}-error`} className="mt-2 block text-sm text-red-300">{error}</span>}</label> }
