"use client";
import { useState } from "react";
import { services, site, whatsappUrl } from "@/content/site";

type Errors = Partial<Record<"name" | "email" | "details" | "consent", string>>;
export default function Contact({ headingLevel = "h2" }: { headingLevel?: "h1" | "h2" }) {
  const [errors, setErrors] = useState<Errors>({});
  function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name") || "").trim(); const email = String(form.get("email") || "").trim(); const details = String(form.get("details") || "").trim(); const next: Errors = {};
    if (!name) next.name = "Enter your name."; if (!/^\S+@\S+\.\S+$/.test(email)) next.email = "Enter a valid email address."; if (details.length < 20) next.details = "Tell us a little more—at least 20 characters."; if (form.get("consent") !== "yes") next.consent = "Confirm that we may respond to this enquiry.";
    if (Object.keys(next).length) { setErrors(next); requestAnimationFrame(() => document.getElementById(`${Object.keys(next)[0]}-field`)?.focus()); return; }
    setErrors({}); const subject = encodeURIComponent(`Project enquiry from ${name}`); const body = encodeURIComponent(`Name: ${name}\nBusiness: ${form.get("business")}\nEmail: ${email}\nTelephone: ${form.get("phone")}\nService: ${form.get("service")}\nBudget: ${form.get("budget")}\nTimeline: ${form.get("timeline")}\n\nProject:\n${details}`); window.location.href = `mailto:${site.email}?subject=${subject}&body=${body}`;
  }
  const field = "mt-2 w-full min-w-0 rounded-[var(--radius-sm)] border border-white/15 bg-black/40 px-4 py-3 text-white transition-colors placeholder:text-white/35 hover:border-white/25 focus:border-[#C8A348]"; const Heading = headingLevel;
  return <section id="contact" className="section-space border-t border-white/10 bg-[#060606] px-4 sm:px-8"><div className="mx-auto grid min-w-0 max-w-7xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><div className="min-w-0"><p className="eyebrow">Start a project</p><Heading className="section-title mt-5 text-balance">Tell us what needs to become memorable.</Heading><p className="mt-6 leading-8 text-gray-300">Share the context, not a polished brief. Your answers prepare an email in your own mail app; nothing is silently submitted or stored.</p><div className="mt-8 border-l border-[#c8a348]/50 pl-5"><p className="text-sm font-semibold text-white">What happens next</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">Once you send the prepared email, we review fit, scope and timing before suggesting the clearest next step.</p></div><a className="link-arrow mt-7 inline-flex" href={whatsappUrl("Hi Prime Presence, I'd like to discuss a project.")} target="_blank" rel="noreferrer">Prefer WhatsApp? {site.phoneDisplay} <span aria-hidden="true">→</span></a></div>
  <form onSubmit={submit} noValidate className="grid min-w-0 gap-5 rounded-[var(--radius-lg)] border border-white/10 bg-[#0b0b0b] p-6 sm:grid-cols-2 sm:p-8" aria-label="Project enquiry">
    <Field label="Name" required error={errors.name}><input id="name-field" name="name" required autoComplete="name" className={field} aria-invalid={Boolean(errors.name)} aria-describedby={errors.name ? "name-error" : undefined} /></Field><Field label="Business name"><input name="business" autoComplete="organization" className={field} /></Field>
    <Field label="Email" required error={errors.email}><input id="email-field" name="email" required type="email" autoComplete="email" className={field} aria-invalid={Boolean(errors.email)} aria-describedby={errors.email ? "email-error" : undefined} /></Field><Field label="Telephone"><input name="phone" type="tel" autoComplete="tel" inputMode="tel" className={field} /></Field>
    <Field label="Service"><select name="service" className={field}>{services.map(service => <option key={service.slug}>{service.title}</option>)}</select></Field><Field label="Approximate budget"><select name="budget" className={field}><option>Not decided yet</option><option>R10,000–R25,000</option><option>R25,000–R50,000</option><option>R50,000+</option></select></Field>
    <Field label="Preferred timeline"><select name="timeline" className={field}><option>Flexible</option><option>Within 1 month</option><option>1–3 months</option><option>3+ months</option></select></Field><div className="hidden sm:block" aria-hidden="true" />
    <Field label="Project details" required error={errors.details} wide><textarea id="details-field" name="details" required minLength={20} className={`${field} min-h-40 resize-y`} aria-invalid={Boolean(errors.details)} aria-describedby={errors.details ? "details-error" : "details-help"} /><span id="details-help" className="mt-2 block text-xs text-[var(--muted)]">What are you building, changing, or preparing to launch?</span></Field>
    <div className="sm:col-span-2"><label className="flex items-start gap-3 text-sm leading-6 text-gray-300"><input id="consent-field" name="consent" value="yes" required type="checkbox" aria-invalid={Boolean(errors.consent)} aria-describedby={errors.consent ? "consent-error" : undefined} className="mt-1 h-5 w-5 shrink-0 accent-[#c8a348]" />I agree that Prime Presence may use these details to respond to my enquiry.</label><a href="/privacy" className="ml-8 mt-2 inline-flex text-sm text-[#f0d788] underline underline-offset-4">Read the privacy policy</a>{errors.consent && <p id="consent-error" className="mt-2 text-sm text-red-300">{errors.consent}</p>}</div>
    <button className="button-primary sm:col-span-2" type="submit">Prepare enquiry email</button><p className="text-center text-xs leading-5 text-[var(--muted)] sm:col-span-2">You will review and send the message from your email application.</p>
  </form></div></section>;
}

function Field({ label, required, error, wide, children }: { label: string; required?: boolean; error?: string; wide?: boolean; children: React.ReactNode }) { const id = label === "Project details" ? "details" : label.toLowerCase().split(" ")[0]; return <label className={`min-w-0 ${wide ? "sm:col-span-2" : ""}`}><span className="text-sm font-medium text-gray-200">{label}{required && <span aria-hidden="true"> *</span>}</span>{children}{error && <span id={`${id}-error`} className="mt-2 block text-sm text-red-300">{error}</span>}</label> }
