"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";

const links = [["Work", "/work"], ["Services", "/services"], ["Process", "/process"], ["About", "/about"], ["Contact", "/contact"]] as const;
export default function Navbar({ siteName }: { siteName: string }) {
  const pathname = usePathname(); const [open, setOpen] = useState(false); const toggle = useRef<HTMLButtonElement>(null); const firstLink = useRef<HTMLAnchorElement>(null); const menu = useRef<HTMLDivElement>(null);
  useEffect(() => { const background = document.querySelectorAll<HTMLElement>("main, footer"); document.body.style.overflow = open ? "hidden" : ""; background.forEach(element => { element.inert = open; }); if (open) firstLink.current?.focus(); const handleKey = (event: KeyboardEvent) => { if (event.key === "Escape") { setOpen(false); toggle.current?.focus(); return; } if (event.key !== "Tab" || !open || !menu.current || !toggle.current) return; const focusable = [toggle.current, ...menu.current.querySelectorAll<HTMLElement>('a[href], button:not([disabled])')]; const first = focusable[0], last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; window.addEventListener("keydown", handleKey); return () => { document.body.style.overflow = ""; background.forEach(element => { element.inert = false; }); window.removeEventListener("keydown", handleKey); }; }, [open]);
  return <><header className="fixed inset-x-0 top-0 z-[var(--z-nav)] border-b border-white/10 bg-black/80 backdrop-blur-xl"><nav aria-label="Primary" className="container-site flex h-20 items-center justify-between"><Link href="/" className="min-h-11 py-2 text-xs font-semibold uppercase tracking-[.3em] text-[#C8A348]">{siteName}<span className="mt-1 block text-[10px] tracking-[.2em] text-white/60">Atelier</span></Link><ul className="hidden items-center gap-7 lg:flex">{links.map(([label, href]) => <li key={href}><Link aria-current={pathname === href || pathname.startsWith(`${href}/`) ? "page" : undefined} className="relative flex min-h-11 items-center text-xs font-semibold uppercase tracking-[.16em] text-white transition-colors hover:text-[#C8A348] aria-[current=page]:text-[#f0d788]" href={href}>{label}</Link></li>)}</ul><div className="flex items-center gap-3"><div className="hidden sm:block"><Link className="button-secondary" href="/contact">Start a Project</Link></div><button ref={toggle} type="button" aria-expanded={open} aria-controls="mobile-menu" aria-label={open ? "Close menu" : "Menu"} onClick={() => setOpen(!open)} className="flex min-h-11 min-w-16 items-center justify-center rounded-full border border-white/20 px-3 text-xs font-semibold uppercase tracking-[.08em] lg:hidden">{open ? "Close" : "Menu"}</button></div></nav></header><div ref={menu} id="mobile-menu" aria-hidden={!open} className={`fixed inset-0 z-40 bg-[#050505] px-6 pb-10 pt-28 lg:hidden ${open ? "block" : "hidden"}`}><nav aria-label="Mobile" className="flex flex-col gap-1">{links.map(([label, href], index) => <Link ref={index === 0 ? firstLink : undefined} aria-current={pathname === href ? "page" : undefined} key={href} onClick={() => setOpen(false)} className="border-b border-white/10 py-5 text-2xl font-semibold aria-[current=page]:text-[#f0d788]" href={href}>{label}</Link>)}</nav><Link onClick={() => setOpen(false)} className="button-primary mt-8 flex w-full" href="/contact">Start a Project</Link></div></>;
}
